name: Check Commits

jobs:
  check_commit:
    runs-on: ubuntu-latest
    name: Check commit style
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check commit style
        uses: cyberark/enforce-commit-style@v1
