name: Check Commits

on:
  pull_request:
    branches: [ master ]
    types: [opened, synchronize, reopened, edited]


jobs:
  check_commit:
    runs-on: ubuntu-latest
    name: Check commit style
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check commit style
        uses: cyberark/enforce-commit-style@test

  rebase:
    runs-on: ubuntu-latest
    name: Rebase
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check commit style
        uses: cyberark/enforce-rebase@v2
